### ISSUE TITLE
ReferenceError: Can't find variable: document

### ISSUE THREAD

**Issue by ploveland** [symisc/faceio-npm#16]
https://github.com/symisc/faceio-npm/blob/233e8d35777fa920088a3a4dc648042555a4ed3e/index.js#L8C34-L8C34

**Comment by symisc** [comment]
Hello,

- First and foremost **React != React Native** This should help you to dig around and will of course help to why the **document is not available**.
- The _fio.js_ library is intended for web applications that run in the browser. When running in the context of a browser, the document element is available by default.
- Now, the fix is to install the **[React Webview component](https://github.com/react-native-webview/react-native-webview)** and [instantiate](https://faceio.net/integration-guide) _fio.js_  inside the Webview. 
- Refer to the forum question at: [How Do I Implement FACEIO (fio.js) on My React Native App?](https://community.faceio.net/threads/how-i-can-do-that-it-would-be-of-great-help-widget-15 ) for additional information.

**Comment by Yogesh9725** [comment]
@symisc Do you Have an any code solution ?
