### ISSUE TITLE
Livneness Detection & Face Anti-Spoofing should be included in starter plans

### ISSUE THREAD

**Issue by NaturalDevCR** [symisc/faceio-npm#8]
This security function should be included in the starter plan, without something so basic like this for a face authentication, it makes no sense to even pay the starter plan, which should already include basic functionality like this.... 

If face recognition is displayed as an authentication system every paid plan should have this included. Please consider this, otherwise it makes no sense to pay $20 more for a basic functionality that compromises the whole idea of authentication with FaceIO.

**Comment by symisc** [comment]
[Liveness Detection & Face Anti-Spoofing](https://blog.pixlab.io/2023/02/face-spoofing-livneness-detection-and-presentation-attacks-prevention-security-feature-available-for-faceio) are security features available starting from the [Business Plan](https://faceio.net/pricing), and up due to the **heavy computing power they require to operate**.

Nevertheless, there is an **extra layer of security** offered to all plans which is [PIN Code enforcement](https://faceio.net/security-best-practice#enforcePin) that is **automatically activated by default** for each new FACEIO application you create. Whether they try to spoof or not, users have to **confirm their PIN Code** in order to gain access.

Finally,  you still have very [important security options](https://faceio.net/security-best-practice) available on the Starter Plan, such as Face Duplication Prevention, [Minor Access Restriction](https://blog.pixlab.io/2023/06/age-verification-check-available-for-faceio-face-recognition), and so on.
